SN/SN/urls.py
from django.contrib import admin
from django.conf.urls import url, include
# from django.urls import re_path
from django.conf.urls.static import static
from django.conf import settings

from accounts.views import home_view


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),

    url(r'^chats/', include(('chats.urls', 'chats'), namespace='chats')),

    url(r'^posts/', include(('posts.urls', 'posts'), namespace='posts')),
    url(r'^comments/', include(('comments.urls', 'comments'), namespace='comments')),
    url(r'^likes/', include(('likes.urls', 'likes'), namespace='likes')),

    url(r'^password_reset/', include(('password_reset.urls', 'password_reset'), namespace='password_reset')),

    url(r'^$', home_view, name='home'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SN/accounts/urls.py
from django.conf.urls import url, include
from django.urls import re_path
from django.contrib import admin


from .views import (
    login_view, 
    register_view, 
    logout_view,
    profile_view,
    profile_update,
    profile_delete,
    profile_list,
    )

urlpatterns = [
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^profile/(?P<slug>[\w-]+)/$', profile_view, name='profile'),
    url(r'^profile/(?P<slug>[\w-]+)/update/$', profile_update, name='update'),
    url(r'^profile/(?P<slug>[\w-]+)/delete/$', profile_delete, name='delete'),
    url(r'^profile_list/$', profile_list, name='profile_list'),
]

SN/chats/urls.py
from django.conf.urls import url
from django.urls import re_path
from django.contrib import admin


from .views import (
	chat_list,

    chat_create,

	message_create,
    
	# message_detail,
	# message_update,
	# message_delete,
	# last_10_msgs,
	# message_statistics,
	# answer,
	chat_detail,
	# chat_update,
	chat_delete,
	update_msgs,
	update_chats,
	)
# :chats/create/
# :chats/list/

# :chats/that
# :chats/another

# :chats/msg
urlpatterns = [
    # url(r'^message_create/$', message_create, name='message_create'),
    # ( proflie slugs ) or custom slug based on chat_name created via model form
    url(r'^chat_create/$', chat_create, name='chat_create'), # /(?P<slug>[\w-]+)/(?P<auto>[\d-])

	url(r'^list/$', chat_list, name='chat_list'),

	# url(r'^list/(?P<id>[\w-]+)/forward/$', message_forward, name='message_forward'),

	# should be partly visible ( chat slugs )
	url(r'^chat/(?P<slug>[\w-]+)/$', chat_detail, name='chat_detail'), # enter chat to see msgs and send messagges
    # url(r'^chat/(?P<slug>[\w-]+)/edit/$', chat_update, name='chat_update'), # auto should be
    url(r'^chat/(?P<slug>[\w-]+)/delete/$', chat_delete, name='chat_delete'),

# should be unvisible
    url(r'^chat/(?P<slug>[\w-]+)/message_create/$', message_create, name='message_create'),
    # url(r'^chat/(?P<slug>[\w-]+)/msg/(?P<id>[\w-]+)/$', message_detail, name='message_detail'),
    # url(r'^chat/(?P<slug>[\w-]+)/msg/(?P<id>[\w-]+)/edit/$', message_update, name='message_update'),
    # url(r'^chat/(?P<slug>[\w-]+)/msg/(?P<id>[\w-]+)/delete/$', message_delete, name='message_delete'),

	# url(r'^statictics/', message_statistics, name='message_statistics'),
	# url(r'^thread/(?P<slug>[\w-]+)/answer/$', answer, name='answer'),
	url(r'^chat/(?P<slug>[\w-]+)/update/$', update_msgs, name='update_msgs'), # for 1 chat (like chat detail)

	url(r'^list/update/$', update_chats, name='update_chats'),
]

SN/templates/base.html
{% load static %}
<!--DOCTYPE html -->
<html>
<head>
<title>{% block head_title %}Social Network{% endblock head_title %}</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' >


<link rel='stylesheet' href='{% static "css/main.css" %}' />


{% block head_extra %} {% endblock head_extra %}
</head>
<body>

<nav class='container'> 
    <ol class='breadcrumb'>
        {% if request.user.is_authenticated %}
        <li><a href='{{ request.user.profile.get_absolute_url }}'>Home</a></li>
        {% endif %}
        <li><a href='{% url "chats:chat_list" %}'>Chats</a></li>
        {% block chat_detail_link %}
        {% endblock %}

        {% if not request.user.is_authenticated %}
        <li class='pull-right'><a href='{% url "accounts:register" %}'>Register</a></li>
        <li class='pull-right'><a href='{% url "accounts:login" %}'>Login</a></li>
        {% else %}
        <li class='pull-right'><a href='{% url "accounts:logout" %}'>Logout</a></li>
        <li class='pull-right dropdown'>
          <a class="dropdown-toggle" href="#" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings</a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><a href="{% url 'accounts:profile_list' %}">Search for the user</a></li>
            <li><a href="#">Действие 2</a></li>
          </ul>
          </li>

        {% endif %}

    </ol>
{% block content %}{% endblock content %}
</nav>




<!-- Latest compiled and minified JavaScript -->
<script src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>

<script>
  var csrf_token = '{{ csrf_token }}'
</script>
<!-- for post deletion for app posts -->
<script src='{% static "js/chat_operations.js" %}'></script>
<script src='{% static "js/mail_form.js" %}'></script>
<script src='{% static "js/profile_form.js" %}'></script>
<script src='{% static "js/mail_list.js" %}'></script>
</body>
</html>

SN/templates/chat_detail.html
{% extends base_template %}
{% load static %}
{% block head_title %}
    {{theme}}
{% endblock head_title %}


{% block chat_detail_link %}
  <li><a href='{{ chat_instance.get_absolute_url }}'>{{ chat_instance.chat_name }}</a></li>
{% endblock chat_detail_link %}
{% block content %}
<h1>CHAT {{ chat_instance.chat_name }}</h1>
<hr width='10%' style="height:5px;border:none;">

<section class='container-fluid-sm|md|lg|xl msgs_in_chat'>
{% include 'to_render_msgs.html' %}
</section>

<article class='create_msg'>
    <p><a data-to-url="{{ chat_instance.create_msg }}" onclick="create_msg(this)" class="btn btn-primary" role="button">Create Message</a></p>
</article>

<div id='update_msgs_url' data-url='{% url "chats:update_msgs" slug=chat_instance.slug %}'></div>

<script src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>
<script src='{% static "js/update_msgs.js" %}'></script>
{% endblock content %}

SN/templates/chat_list.html
{% extends base_template %}
{% load static %}
{% block content %}


<div class='container'>
<div class='row'>
<article class='create_custom_chat'>
    <p><a data-to-url='{% url "chats:chat_create" %}' onclick="create_custom_chat(this)" class="btn btn-default" role="button">Create Custom Chat</a></p>
</article>
</div>

<hr>
<div class='row'>
<section class='col-sm-2 col-sm-offset-5'>
    <h1>List</h1>
</section>
</div>
<hr>

<section class='container col-lg-10 col-lg-offset-3 col-sm-10 col-sm-offset-3 search'>
<form method='GET' action='' class='row'>
<div class='col-lg-6 col-sm-6'>
    <div class='input-group'>
        <input class='form-control' type='text' name='q' placeholder='Search chats' value='{{ request.GET.q }}'/>
        <span class='input-group-btn'>
            <!-- <input class='btn btn-default' type='submit' value='Search' /> -->
            <button class='btn btn-default' type='submit'>Search <i class="fa fa-search"></i></button>
        </span>
    </div>
</div>
</form>
</section>

        
<section class='container page-center main_list_chats'>
{% include 'sublists/main_list_chats.html' %}
</section>

<footer class='footer'>
{% if is_paginated %}
    <div class="container pagination">
        <span class="step-links col-lg-3 col-lg-offset-4 col-sm-3 col-sm-offset-4">
            {% if chat_list.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ chat_list.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ chat_list.number }} of {{ chat_list.paginator.num_pages }}.
            </span>
    
            {% if chat_list.has_next %}
                <a href="?page={{ chat_list.next_page_number }}">next</a>
                <a href="?page={{ chat_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endif %}
</footer>


{% if request.GET.q != None or request.GET.page != None %}
<div id='manage_timeouts' data-to-manage='Off'></div>
{% else %}
<div id='manage_timeouts' data-to-manage='On'></div>
{% endif %}

<div id='update_chats_url' data-url='{% url "chats:update_chats" %}'></div>

<script src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>
<script src='{% static "js/update_chats.js" %}'></script>
<!-- <div id='main_list_msgs'></div> -->
{% endblock content %}

SN/templates/create_chat_form.html
{% load crispy_forms_tags %}

{% block head_extra %} 
{{ c_form.media }}
{% endblock head_extra %}


{% block create_chat %}
<div><small><i>{{ error_c_form }}</i></small></div>
<!-- <button type='button' id="write-msg" class='btn btn-default' value='Write Message' /> -->

<div class='container'>
    <div class="row">
    <h1>Chat</h1>
    <hr/>
        <div class="col-sm-12 col-sm-offset-2"> 
             
            <form method='POST' id='create_custom_chat_form' action='' enctype='multipart/form-data'>
                {{ c_form|crispy }}
            </form>
            <button type='button' data-to-url='{% url "chats:chat_create" %}' onclick="for_form_ccc(this)" class="btn btn-primary" role="button" >Create Custom Chat</button>

        </div>
    </div>
</div>
<div id='error-msg'></div>
{% endblock create_chat %}

SN/templates/create_msg_form.html
{% load crispy_forms_tags %}
{% block head_extra %} 
{{ m_form.media }}
{% endblock head_extra %}
{% block create_msg %}

<div class="container">
    <div class="row">
    <h1>Message</h1>
    <hr/>
        <div class="col-sm-12 col-sm-offset-2"> 
             
            <form method="POST" id="create_msg_form" action="" enctype="multipart/form-data">
                {{ m_form|crispy }}
            </form>
            <button type="button" data-to-url="{{ chat_instance.create_msg }}" onclick="send_msg(this)" class="btn btn-primary" role="button">Send Message</button>

        </div>
    </div>
</div>
<div id="error-msg"></div>
{% endblock create_msg %}

SN/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='{{ title }}' />
</form>
</div>
{% endblock content %}

SN/templates/home.html
{% extends "base.html" %}

{% block content %}
<h2><b>Hello (go to self profile or signup or login)</b></h2>
<h3><i>(go to self profile or signup or login)</i></h3>
{% endblock content %}

SN/templates/message_detail.html
{% extends "base.html" %}
<!--  load urlify  -->
{% load crispy_forms_tags %}
{% load pool_extras %}
{% block head_title %}
{{ topic }} | {{ block.super }}
{% endblock head_title %}


 {% block mail_detail_link %}
  <li><a href='{{ instance.get_absolute_url }}'>{{ topic }}</a></li>
{% endblock mail_detail_link %}



{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
    {% if instance.image %}
    <img src='{{ instance.image.url }}' class='img-responsive' />
    {% endif %} 
<h1>Topic: {{ topic }} <small>{{ instance.created }}</small></h1>
<hr/>
<!-- {% if instance.read_time|time:"i" <= "01" %} < 1 minute {% else %}{{ instance.read_time|time:"i" }} minutes {% endif %} -->


<p>Read time: {% if instance.read_time <= 1 %} < 1 Minute {% else %}{{ instance.read_time }} minutes {% endif %}</p>
<p><a href="{{ instance.sender.get_absolute_url }}">Author: {{ instance.sender.user.username }}</a></p>


<p>Has been send for: </p>
{% for receiver in instance.receivers.all|iterate_queryset %}
  <a href="{{ receiver.get_absolute_url }}">{{ receiver.user.username }}</a>{% if forloop.counter == instance.receivers.all|length %}.{% else %},{% endif %}
{% endfor %}

<p>{{ instance.get_markdown }}</p>

<!-- <p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div> -->
{% if request.user.is_authenticated %}
<!-- <h1> User auth: {{ request.user }}</h1> -->
  
  <!-- <p><a href="{{ instance.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>  -->
  <hr/>
  {% if request.user == instance.sender.user %}
    <p><a data-slug="{{ instance.slug }}" data-to-url="{{ instance.get_delete_url }}" data-detail='True' id="chat_operations" onclick="delete_mail(this)" class="btn btn-danger" role="button">DELETE</a></p>
  {% endif %}
<hr>

{% endif %}
<!-- </p> -->

{% endblock content %}

SN/templates/message_list.html
{% extends "base.html" %}

{% block content %}
{% load pool_extras %}
<h3><a href="{% url 'mails:create' %}">Send Mail</a></h3>
<section class='col-sm-2 col-sm-offset-5'>
    <h1>List</h1>
</section>
{% if type == "last_10_msgs" %}
<section class='page-center container col-sm-8' id='last_10_msgs' data-to-url="{% url 'mails:last_10_msgs' auto_update=1 %}">
    {% load static %}
    <img src="{% static '/pics/loading2.gif' %}" alt="animated" class="img-responsive" />
</section>
{% elif type == "main_list_msgs" %}
<section class='page-center'>
{% include 'sublists/main_list_msgs.html' %}
</section>
<!-- <div id='main_list_msgs'></div> -->
{% endif %}
{% endblock content %}

SN/templates/profile.html
{% extends 'base.html' %}

{% block head_title %}
    {{ profile.user.username }} 
{% endblock head_title %}

{% block content %}

<div class='col-sm-6 col-sm-offset-3'>
    <div>
        <h1>username: <b>{{ profile.user.username }}</b></h1>
        <hr>
        <h1><i>BIO</i></h1>
        <br/>
        {{ profile.get_markdown }}
    </div>
    <!-- TODO imagefield -->
    <br/>
    <small>Birth Date:  {{ profile.birth_date|date:'Y-m-d' }}</small>
    <br/>
    <small>Location:  {{ profile.location }}</small>
    <br/>
    <small>On site from:  {{ profile.user.date_joined|date:'Y-m-d' }}</small>
    <br/>
    <small>Avatar 
        {% if profile.image %}
        <img src='{{ profile.image.url }}' class='img-responsive' />
       {% endif %}
    </small>
    <br/>
</div>

{% if user.profile == profile %}
    <hr/>
    <p><a href="{{ profile.get_update_url }}" id="update_account"  class="btn btn-info" role="button">UPDATE ACCOUNT INFO</a></p>

    <hr/>
    <p><a href="{{ profile.get_password_reset }}" id="password_reset_start"  class="btn btn-info" role="button">PASSWORD RESET</a></p>

    <hr/>
    <p><a href="{{ profile.get_delete_url }}" id="delete_account"  class="btn btn-danger" role="button">DELETE ACCOUNT</a></p>

    {% else %}
    <form method='POST' action='{% url "chats:chat_create" %}' enctype='multipart/form-data'>{% csrf_token %}
        <input type='hidden' name='slug' value='{{ profile.slug }}' />
        <input type='submit' class='btn btn-default' value='Send Message (Start Chat)' />
    </form>
{% endif %}

{% endblock content %}

SN/templates/profile_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{ theme }} 
{% endblock head_title %}

{% block head_extra %} 
{{ form.media }}

{% endblock head_extra %}



{% block content %}
<div class='col-sm-6'>
<h1>Bio Preview</h1>
<hr/>
<div class='content-preview'>
    <h3 id='preview-title'></h3>
    <p id='preview-content'></p>
</div>
</div>
<div class='col-sm-6'>
<h1>Form</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Update Profile' />
</form>
</div>
{% endblock content %}

SN/templates/profile_list.html
{% extends base_template %}

{% block content %}


<div class='container'>
<div class='row'>
<section class='col-sm-2 col-sm-offset-5'>
    <h1>List</h1>
</section>
</div>
<hr>
<div class='row'>

<!-- inner list -->
<section class='container col-lg-10 col-lg-offset-3 col-sm-10 col-sm-offset-3 search'>
<form method='GET' action='' class='row'>
<div class='col-lg-6 col-sm-6'>
    <div class='input-group'>
        <input class='form-control' type='text' name='q' placeholder='Search profiles' value='{{ request.GET.q }}'/>
        <span class='input-group-btn'>
            <button class='btn btn-default' type='submit'>Search <i class="fa fa-search"></i></button>
        </span>
    </div>
</div>
</form>
</section>



<section class='container profile-list'>
{% for profile in profile_list %}
<div class="row">
    <div class="thumbnail">
    <div class="caption profile-detail-item">
        <h3><a href='{{ profile.get_absolute_url }}'>{{ profile.user.username }}</a> <small>profile_image</small></h3>
    </div>
    </div>
</div>
{% endfor %}
</section>

<footer class='footer'>
{% if is_paginated %}
    <div class="container pagination">
        <span class="step-links col-lg-3 col-lg-offset-4 col-sm-3 col-sm-offset-4">
            {% if profile_list.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ profile_list.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ profile_list.number }} of {{ profile_list.paginator.num_pages }}.
            </span>
    
            {% if profile_list.has_next %}
                <a href="?page={{ profile_list.next_page_number }}">next</a>
                <a href="?page={{ profile_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endif %}
</footer>

</div>
</div>
<!-- <div id='main_list_msgs'></div> -->
{% endblock content %}

SN/templates/to_render_msgs.html
{% for msg in chat_instance.get_inner_msgs %}
    <div class='row bg-primary text-white row-margin msg_id_{{msg.id}}'>
        <div class='col-sm-12'> 
            content: {{msg.content}}
        </div>
        <div class='col-sm-3'>
            sender: {{msg.sender.user.username}}
        </div>
        <div class='col-sm-3'>
            created: {{msg.created}}
        </div>
        {% if msg.is_msg_updated %}
            <div class='col-sm-3'>
                updated: {{msg.updated}}
            </div>
        {% endif %}
        {% if msg.image %}
            <div class='col-sm-3'>
                image: {{msg.image.url}}
            </div>
        {% endif %}
    </div>
    <!-- <hr width='10%'  style="height:0px;border:none;"> -->
{% endfor %}

SN/templates/ultimate_form.html
{% extends base_template  %}

{% load crispy_forms_tags %}

{% block head_title %}
    {{ theme }} 
{% endblock head_title %}

{% block head_extra %} 
{{ m_form.media }}

{% endblock head_extra %}



{% block content %}
<div class='col-sm-6'>
<h1>Bio Preview</h1>
<hr/>
<div class='content-preview'>
    <h3 id='preview-title'></h3>
    <p id='preview-content'></p>
</div>
</div>
<div class='col-sm-6'>
<h1>Form</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ m_form|crispy }}
<input type='submit' class='btn btn-default' value='Confirm' id='submit' data-to-url="{% url 'chats:answer' %}"/>
</form>
</div>
{% endblock content %}